// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8HdSlrgrOSJCAGpBBjRwyNpd5yBf2dkc',
    appId: '1:472720851938:web:6ea7c49daa8285db516fbb',
    messagingSenderId: '472720851938',
    projectId: 'apertureflow-bc502',
    authDomain: 'apertureflow-bc502.firebaseapp.com',
    storageBucket: 'apertureflow-bc502.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl8X8qv7BhhusC8iJByWK6Zmuuja7n8Mg',
    appId: '1:472720851938:android:c26ae87f15af2a8d516fbb',
    messagingSenderId: '472720851938',
    projectId: 'apertureflow-bc502',
    storageBucket: 'apertureflow-bc502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCibjqxcOZZ-GolfgzITj3we-q_8om6EcA',
    appId: '1:472720851938:ios:4d75ea474bb17187516fbb',
    messagingSenderId: '472720851938',
    projectId: 'apertureflow-bc502',
    storageBucket: 'apertureflow-bc502.firebasestorage.app',
    iosBundleId: 'com.example.apertureflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCibjqxcOZZ-GolfgzITj3we-q_8om6EcA',
    appId: '1:472720851938:ios:4d75ea474bb17187516fbb',
    messagingSenderId: '472720851938',
    projectId: 'apertureflow-bc502',
    storageBucket: 'apertureflow-bc502.firebasestorage.app',
    iosBundleId: 'com.example.apertureflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8HdSlrgrOSJCAGpBBjRwyNpd5yBf2dkc',
    appId: '1:472720851938:web:c8bdac95a143ef07516fbb',
    messagingSenderId: '472720851938',
    projectId: 'apertureflow-bc502',
    authDomain: 'apertureflow-bc502.firebaseapp.com',
    storageBucket: 'apertureflow-bc502.firebasestorage.app',
  );
}
